# Generated by Django 5.1.4 on 2025-02-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogParsingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_parsed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
