# Generated by Django 5.1.4 on 2025-02-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0002_logparsingstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogParsingStatus',
        ),
        migrations.AlterUniqueTogether(
            name='alertlogs',
            unique_together={('timeStamp', 'message')},
        ),
        migrations.AlterUniqueTogether(
            name='resourceusagelogs',
            unique_together={('timeStamp', 'message')},
        ),
        migrations.AlterUniqueTogether(
            name='suspiciouslogs',
            unique_together={('timeStamp', 'message')},
        ),
        migrations.AlterUniqueTogether(
            name='watchlistlogs',
            unique_together={('timeStamp', 'message')},
        ),
    ]
