# Generated by Django 5.1.4 on 2025-03-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0003_delete_logparsingstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaliciousPackets',
            fields=[
                ('log_Id', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField()),
                ('message', models.TextField()),
            ],
            options={
                'unique_together': {('timeStamp', 'message')},
            },
        ),
        migrations.CreateModel(
            name='SuspiciousPackets',
            fields=[
                ('log_Id', models.AutoField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField()),
                ('message', models.TextField()),
            ],
            options={
                'unique_together': {('timeStamp', 'message')},
            },
        ),
    ]
