# Generated by Django 5.1.4 on 2025-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0004_maliciouspackets_suspiciouspackets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage', models.FloatField()),
                ('ram_usage', models.FloatField()),
                ('ram_used', models.FloatField()),
                ('ram_total', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('disk_used', models.FloatField()),
                ('disk_total', models.FloatField()),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
