# Generated by Django 5.1.4 on 2025-03-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0005_systemmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemmetrics',
            name='disk_usage',
            field=models.FloatField(null=True),
        ),
    ]
