# Generated by Django 5.1.4 on 2025-03-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0006_alter_systemmetrics_disk_usage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemmetrics',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='systemmetrics',
            old_name='disk_total',
            new_name='disk_read',
        ),
        migrations.RenameField(
            model_name='systemmetrics',
            old_name='disk_used',
            new_name='disk_write',
        ),
        migrations.RemoveField(
            model_name='systemmetrics',
            name='disk_usage',
        ),
        migrations.RemoveField(
            model_name='systemmetrics',
            name='ram_total',
        ),
        migrations.RemoveField(
            model_name='systemmetrics',
            name='ram_usage',
        ),
        migrations.AddField(
            model_name='systemmetrics',
            name='is_application_only',
            field=models.BooleanField(default=False),
        ),
    ]
