# Generated by Django 5.1.4 on 2025-04-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0007_alter_systemmetrics_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maliciouspackets',
            options={'verbose_name_plural': 'Malicious Packets'},
        ),
        migrations.AlterModelOptions(
            name='suspiciouspackets',
            options={'verbose_name_plural': 'Suspicious Packets'},
        ),
        migrations.AddField(
            model_name='maliciouspackets',
            name='source_ip',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='maliciouspackets',
            name='threat_type',
            field=models.CharField(choices=[('ddos', 'DDoS Attack'), ('sql_injection', 'SQL Injection'), ('exploit', 'Exploit Attempt'), ('xss', 'XSS Attack'), ('brute_force', 'Brute Force Attempt'), ('other', 'Malicious Activity')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='suspiciouspackets',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='suspiciouspackets',
            name='source_ip',
            field=models.CharField(default='N/A', max_length=15),
        ),
    ]
