# Generated by Django 5.1.4 on 2025-04-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0011_remove_trafficalert_packet_remove_trafficalert_rule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('destination_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('source_port', models.PositiveIntegerField(blank=True, null=True)),
                ('destination_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=20)),
                ('length', models.PositiveIntegerField()),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reasons', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='suspicioustraffic',
            name='session',
        ),
        migrations.DeleteModel(
            name='NetworkCaptureSession',
        ),
        migrations.DeleteModel(
            name='SuspiciousTraffic',
        ),
    ]
