# Generated by Django 5.1.4 on 2025-04-26 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0012_networktraffic_remove_suspicioustraffic_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100)),
                ('rule_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='networktraffic',
            options={},
        ),
        migrations.RemoveField(
            model_name='networktraffic',
            name='destination_port',
        ),
        migrations.RemoveField(
            model_name='networktraffic',
            name='length',
        ),
        migrations.RemoveField(
            model_name='networktraffic',
            name='source_port',
        ),
        migrations.RemoveField(
            model_name='networktraffic',
            name='suspicious_reasons',
        ),
        migrations.AddField(
            model_name='networktraffic',
            name='packet_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='networktraffic',
            name='port',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='destination_ip',
            field=models.CharField(default='N/A', max_length=45),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='protocol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='source_ip',
            field=models.CharField(default='N/A', max_length=45),
        ),
        migrations.AlterField(
            model_name='networktraffic',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='NetworkAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('traffic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolkit.networktraffic')),
            ],
        ),
        migrations.AddField(
            model_name='networktraffic',
            name='rule_triggered',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolkit.networkrule'),
        ),
    ]
