# Generated by Django 5.1.4 on 2025-04-26 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0013_networkrule_alter_networktraffic_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networktraffic',
            name='rule_triggered',
        ),
        migrations.CreateModel(
            name='NetworkCaptureSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('interface', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('total_packets', models.IntegerField(default=0)),
                ('suspicious_activities', models.JSONField(default=list)),
                ('traffic_stats', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SuspiciousTraffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('destination_ip', models.CharField(blank=True, max_length=50, null=True)),
                ('protocol', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolkit.networkcapturesession')),
            ],
        ),
        migrations.DeleteModel(
            name='NetworkAlert',
        ),
        migrations.DeleteModel(
            name='NetworkRule',
        ),
        migrations.DeleteModel(
            name='NetworkTraffic',
        ),
    ]
