# Generated by Django 5.1.4 on 2025-05-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0018_networkinterface_packetcapture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('interface', models.CharField(blank=True, max_length=100)),
                ('filter', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
