# Generated by Django 5.1.4 on 2025-05-04 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0019_capturestate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rule_id', models.CharField(max_length=50)),
                ('rule_name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10, null=True)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('packet_size', models.IntegerField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('packet_count', models.IntegerField(default=0)),
                ('capture_file', models.FilePathField(max_length=255, null=True, path='captures/')),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('condition', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alert',
            name='resolved_by',
        ),
        migrations.DeleteModel(
            name='CaptureState',
        ),
        migrations.DeleteModel(
            name='NetworkInterface',
        ),
        migrations.DeleteModel(
            name='PacketCapture',
        ),
        migrations.AddField(
            model_name='networkalert',
            name='capture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolkit.networkcapture'),
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
