# Generated by Django 5.1.4 on 2025-05-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0020_networkalert_networkcapture_networkrule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkcapture',
            name='capture_file',
            field=models.FilePathField(default='', max_length=255, path='captures/'),
        ),
    ]
