# Generated by Django 5.1.4 on 2025-05-08 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0021_alter_networkcapture_capture_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(max_length=512)),
                ('quarantine_path', models.CharField(max_length=512)),
                ('quarantine_time', models.DateTimeField(auto_now_add=True)),
                ('restored', models.BooleanField(default=False)),
                ('restored_time', models.DateTimeField(blank=True, null=True)),
                ('detection_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toolkit.malwaredetectionresult')),
            ],
        ),
    ]
