# Generated by Django 5.1.4 on 2025-05-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0024_blockedip'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity', models.CharField(max_length=1000)),
                ('module', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
