# Generated by Django 5.1.4 on 2025-05-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0025_recentactivity'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recentactivity',
            index=models.Index(fields=['timestamp'], name='toolkit_rec_timesta_409b40_idx'),
        ),
    ]
