# Generated by Django 5.1.4 on 2025-05-20 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0026_recentactivity_toolkit_rec_timesta_409b40_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='networkalert',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='networkalert',
            name='resolution_method',
            field=models.CharField(choices=[('unresolved', 'Unresolved'), ('blocked_ip', 'IP Blocked'), ('quarantined', 'Host Quarantined'), ('false_positive', 'False Positive'), ('patched', 'Vulnerability Patched')], default='unresolved', max_length=20),
        ),
        migrations.AddField(
            model_name='networkalert',
            name='resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='networkalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
