# Generated by Django 5.1.4 on 2025-05-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toolkit', '0027_networkalert_is_resolved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkalert',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='networkalert',
            name='resolution_method',
        ),
        migrations.RemoveField(
            model_name='networkalert',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='networkalert',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='networkalert',
            name='resolved_by',
        ),
    ]
